apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: ansible-portal-private-repo
  namespace: openshift-config
spec:
  connectionConfig:
    url: https://ansible-automation-platform.github.io/ansible-portal-chart/
    # Reference to secret containing GitHub credentials
    basicAuthConfig:
      secretRef:
        name: github-helm-repo-credentials
        namespace: openshift-config
  name: Ansible Portal Chart Repository (Private)
  description: Private Helm charts for Ansible Automation Portal
