redhat-developer-hub:
  global:
    _environment:
      _production: true
    dynamic:
      plugins:
      - package: http://plugin-registry:8080/ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-1.2.0.tgz
        integrity: sha512-vcBXV6KPfZvSH3HUVhPfFsoaEW4Dq9FpmWgsKlxKf+k+5FZ8DHeIHWhguUiEk7v4BMySL2HRLpl070jEEx4s0w==
        disabled: false
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
      - package: http://plugin-registry:8080/ansible-backstage-plugin-catalog-backend-module-rhaap-dynamic-0.1.0.tgz
        disabled: false
        integrity: sha512-p7ws18Yzz9WGXzP/JUP/G8bbcwG2StRd6uwcarCCXszOa/MgByLTd0qH2mcZ4WyG04WXNKGklf/kGer4jn753Q==
      - package: http://plugin-registry:8080/ansible-plugin-backstage-portal-dynamic-0.1.0.tgz
        disabled: false
        integrity: sha512-5eZ6wSOUOlt0WdkzaAevjbD7wKcwoNthpsbXbLumiwAwssgt9D32hk3+2zIQisMNHLlwj/fVhZPeO/PQ6lyQUw==
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-portal:
                signInPage:
                  importName: SignInPage
                providerSettings:
                  - title: Ansible Automation Platform
                    description: Sign in with Ansible Automation Platform
                    provider: ansible.auth.rhaap
                scaffolderFieldExtensions:
                  - importName: AAPTokenFieldExtension
                  - importName: AAPResourcePickerExtension
                dynamicRoutes:
                  - importName: LandingPage
                    path: /
                  - importName: PortalPage
                    path: /portal
                mountPoints:
                  - mountPoint: application/listener
                    importName: LocationListener
      - package: http://plugin-registry:8080/ansible-backstage-plugin-auth-backend-module-rhaap-provider-dynamic-0.1.0.tgz
        disabled: false
        integrity: sha512-lfx1Mg8m+QNysnENvzoj7tpJa9+WrPzny9C/nw0uMw2wnuHju0Vfya1IQL0njfp4Qm4OX/0tmUCZLBi+GnvMkg==
        pluginConfig: {}
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
        disabled: false
  upstream:
    backstage:
      appConfig:
        catalog:
          stitchingStrategy:
            immediate: true
          orphanStrategy: delete
          processingInterval: {seconds: 10}
          pollingInterval: {seconds: 1}
          stitchTimeout: {minutes: 1}
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          rules:
            - allow:
                [Component, System, Group, Resource, Location, Template, API, Users]
          locations:
            - type: url
              target: https://github.com/ansible/ansible-rhdh-templates/blob/main/seed.yaml
              rules:
                - allow: [Template]
            - type: file
              target: /tmp/aap-showcases/all.yaml
              rules:
                - allow: [Template]
          providers:
            rhaap:
              dev:
                schedule:
                  frequency: {hours: 6}
                  timeout: {seconds: 30}
