redhat-developer-hub:
  global:
    _environment:
      _development: true
    imageTagInfo: # Required: Update here or pass using --set
    dynamic:
      plugins:
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-plugin-backstage-rhaap
          disabled: false
          pluginConfig:
            dynamicPlugins:
              frontend:
                ansible.plugin-backstage-rhaap:
                  appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                  dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic
          disabled: false
          pluginConfig:
            dynamicPlugins:
              backend:
                ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-plugin-backstage-rhaap-backend-dynamic
          disabled: false
          pluginConfig:
            dynamicPlugins:
              backend:
                ansible.plugin-backstage-rhaap-backend: null
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-backstage-plugin-catalog-backend-module-rhaap-dynamic
          disabled: false
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-plugin-backstage-portal
          disabled: false
          pluginConfig:
            dynamicPlugins:
              frontend:
                ansible.plugin-backstage-portal:
                  signInPage:
                    importName: SignInPage
                  providerSettings:
                    - title: RHAAP
                      description: Sign in with RHAAP
                      provider: ansible.auth.rhaap
                  scaffolderFieldExtensions:
                    - importName: AAPTokenFieldExtension
                    - importName: AAPResourcePickerExtension
                  dynamicRoutes:
                    - importName: LandingPage
                      path: /
                    - importName: PortalPage
                      path: /portal
                  mountPoints:
                    - mountPoint: application/listener
                      importName: LocationListener
        - package: oci://quay.io/ansible/ansible-backstage-plugins:{{- include "deployment.quay-image-tag" . }}!ansible-backstage-plugin-auth-backend-module-rhaap-provider-dynamic
          disabled: false
          pluginConfig: {}
        - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
          disabled: false
        - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
          disabled: false
  upstream:
    backstage:
      appConfig:
        catalog:
          stitchingStrategy:
            immediate: true
          orphanStrategy: delete
          processingInterval: {seconds: 10}
          pollingInterval: {seconds: 1}
          stitchTimeout: {minutes: 1}
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          rules:
            - allow:
                [Component, System, Group, Resource, Location, Template, API, Users]
          locations:
            - type: url
              target: https://github.com/ansible/ansible-rhdh-templates/blob/devel/all.yaml
              rules:
                - allow: [Template]
            - type: url
              target: https://github.com/ansible/ansible-rhdh-templates/blob/devel/seed.yaml
              rules:
                - allow: [Template]
            - type: file
              target: /tmp/aap-showcases/all.yaml
              rules:
                - allow: [Template]
          providers:
            rhaap:
              dev:
                schedule:
                  frequency: {minutes: 5}
                  timeout: {seconds: 30}
