redhat-developer-hub:
  nameOverride: ansible-portal
  global:
    clusterRouterBase: "apps.ansible-rhdh-dev.testing.ansible.com"
    _environment:
      _development: false
      _production: false
  upstream:
    nameOverride: ansible-portal
    backstage:
      extraEnvVars:
        # ---
        # The default extraEnvVars coming from the RHDH Chart need to
        # be duplicated here - see https://issues.redhat.com/browse/RHIDP-6082
        - name: BACKEND_SECRET
          valueFrom:
            secretKeyRef:
              key: backend-secret
              name: '{{ include "janus-idp.backend-secret-name" $ }}'
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: '{{- include "janus-idp.postgresql.secretName" . }}'
        - name: ENABLE_AUTH_PROVIDER_MODULE_OVERRIDE
          value: "true"
        - name: SEGMENT_WRITE_KEY
          value: "uCMHvkR5n5q2v57LNXHwvTYlGV8lqFR9"
      image:
        registry: quay.io
        repository: rhdh/rhdh-hub-rhel9
        tag: "1.5"
      extraContainers:
        - command:
            - adt
            - server
          image: '{{- include "portal.container-image" . }}'
          imagePullPolicy: IfNotPresent
          name: ansible-devtools-server
          ports:
            - containerPort: 8000
      appConfig:
        enableExperimentalRedirectFlow: true
        ansible:
          rhaap:
            baseUrl: "changeme"
            token: "changeme"
            checkSSL: true
            showCaseLocation:
              type: file
              target: '/tmp/aap-showcases/'
            schedule:
              frequency:
                seconds: 120
              timeout:
                seconds: 5
          creatorService:
            baseUrl: '127.0.0.1'
            port: '8000'
        auth:
          environment: production
          signInPage: rhaap
          providers:
            rhaap:
              production:
                host: "changeme"
                checkSSL: false
                clientId: "changeme"
                clientSecret: "changeme"
                signIn:
                  resolvers:
                    - resolver: usernameMatchingUser
        catalog:
          stitchingStrategy:
            immediate: true
          orphanStrategy: delete
          processingInterval: { seconds: 10 }
          pollingInterval: { seconds: 1 }
          stitchTimeout: { minutes: 1 }
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          rules:
            - allow:
                [Component, System, Group, Resource, Location, Template, API, Users]
          locations:
            - type: url
              target: https://github.com/ansible/ansible-rhdh-templates/blob/main/all.yaml
              rules:
                - allow: [Template]
            - type: url
              target: https://github.com/ansible/ansible-rhdh-templates/blob/main/seed.yaml
              rules:
                - allow: [Template]
            - type: file
              target: /tmp/aap-showcases/all.yaml
              rules:
                - allow: [Template]
          providers:
            rhaap:
              dev:
                schedule:
                  frequency: { minutes: 1 }
                  timeout: { seconds: 5 }
        integrations:
          github:
            - host: github.com
              token: "changeme"
          gitlab:
            - host: gitlab.com
              token: "changeme"
