{{/*
    Validates required values
*/}}

{{- if eq (index .Values "redhat-developer-hub" "upstream" "backstage" "appConfig" "ansible" "rhaap" "token") "changeme" -}}
{{- fail "ansible.rhaap.token is required" -}}
{{- end -}}

{{- if eq (index .Values "redhat-developer-hub" "upstream" "backstage" "appConfig" "ansible" "rhaap" "baseUrl") "changeme" -}}
{{- fail "ansible.rhaap.baseUrl is required" -}}
{{- end -}}

{{- if eq (index .Values "redhat-developer-hub" "upstream" "backstage" "appConfig" "auth" "providers" "rhaap" "production" "host") "changeme" -}}
{{- fail "auth.providers.rhaap.production.host is required" -}}
{{- end -}}

{{- if eq (index .Values "redhat-developer-hub" "upstream" "backstage" "appConfig" "auth" "providers" "rhaap" "production" "clientId") "changeme" -}}
{{- fail "auth.providers.rhaap.production.clientId is required" -}}
{{- end -}}

{{- if eq (index .Values "redhat-developer-hub" "upstream" "backstage" "appConfig" "auth" "providers" "rhaap" "production" "clientSecret") "changeme" -}}
{{- fail "auth.providers.rhaap.production.clientSecret is required" -}}
{{- end -}}

{{- if not (or
    (index .Values "redhat-developer-hub" "global" "_environment" "_production")
    (index .Values "redhat-developer-hub" "global" "_environment" "_development")
) -}}
{{- fail "Either values-prod.yaml or values-dev.yaml must be passed using the --values (or -f) flag" -}}
{{- end -}}

{{- if and
    (index .Values "redhat-developer-hub" "global" "_environment" "_development")
    (not (index .Values "redhat-developer-hub" "global" "imageTagInfo"))
-}}
{{- fail "Quay image tag required for development environment: use `--set global.imageTagInfo=<tag>` or update the value in the values-dev.yaml file" -}}
{{- end -}}
