{{/*
    Validates required values
*/}}

{{- if eq (index .Values "redhat-developer-hub" "global" "clusterRouterBase") "apps.example.com" -}}
{{- fail "Set the clusterRouterBase value to your cluster host base URL." -}}
{{- end -}}

{{- if not (or
    (index .Values "redhat-developer-hub" "global" "_environment" "_production")
    (index .Values "redhat-developer-hub" "global" "_environment" "_development")
) -}}
{{- fail "Set either the production or development environment to true with --set global._environment.[_development, _production]=true" -}}
{{- end -}}

{{- if (and
    (index .Values "redhat-developer-hub" "global" "_environment" "_production")
    (index .Values "redhat-developer-hub" "global" "_environment" "_development")
) -}}
{{- fail "Both production and development environments are set to true, but both cannot be active. Set one to false." -}}
{{- end -}}

{{- if and
    (index .Values "redhat-developer-hub" "global" "_environment" "_development")
    (not (index .Values "redhat-developer-hub" "global" "imageTagInfo"))
-}}
{{- fail "Quay image tag required for development environment: use `--set global.imageTagInfo=<tag>` or update the value in the values-dev.yaml file" -}}
{{- end -}}
