name: Release Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Package Helm Chart
        run: |
          helm package . --destination ./packaged-charts/

      - name: Update Helm Repository Index
        run: |
          # Create or update index.yaml
          if [ -f index.yaml ]; then
            helm repo index ./packaged-charts/ --url https://ansible-automation-platform.github.io/ansible-portal-chart/ --merge index.yaml
          else
            helm repo index ./packaged-charts/ --url https://ansible-automation-platform.github.io/ansible-portal-chart/
          fi
          mv ./packaged-charts/index.yaml .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update Helm repository'
