name: 'Renovate'

on:
  schedule:
    # Run Renovate every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.16
