name: Test Charts

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "renovate.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test-chart:
    strategy:
      fail-fast: false
      matrix:
        version:
          # 'latest' is the latest RC or stable release of RHDH (built from a release branch)
          - "1.5"
        experimental: [false]
        include:
          # 'next' is the upcoming release of RHDH
          # (built from the RHDH main branch, so might be unstable)
          - version: "1.6"
            experimental: true

    name: Test ${{ matrix.version == 'latest' && 'Latest' || matrix.version }} Release
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.10.0